title: Tran K Nguyen # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  High energy problem-solver with a strong passion for design thinking
  <br><br>
  Python enthusiast
  <br><br>
  <a href="https://www.linkedin.com/in/tranknguyen/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
